image: python:3

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - LT_USERNAME=<your LambdaTest username> LT_ACCESS_KEY=<your LambdaTest access key> python test.py

9.	Push your changes to GitHub using the following commands: 
git add .
git commit -m "Add .gitlab-ci.yml file"
git push origin main
